name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3
      - name: Test using Gradle
        run: gradle test